using UnityEngine;

public class Item : MonoBehaviour
{
    [field : SerializeField] public ItemSO itemData { get; private set; }   //嬴檜蠱 薑爾 婦溼 Scriptable Object

    [SerializeField] private int count = 1;
    public int Count
    {
        get { return count; }
        set
        {
            if (value <= 0)
                value = 0;
            else if (value > itemData.maxCount)
                value = itemData.maxCount;

            count = value;

            if(count <= 0)
            {
                ItemPool.Instance.TakeObjects(this);
            }
        }
    }

    private void OnEnable()
    {
        Count = 1;
    }
}
