using System.Collections;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.Rendering;
using UnityEngine.Tilemaps;

[RequireComponent(typeof(Rigidbody2D))]
public class PlayerController : MonoBehaviour
{
    [SerializeField] private Rigidbody2D playerRigid;
    [SerializeField] private Animator playerAnim;

    [SerializeField] private Tool[] tools;

    [field: SerializeField] public float MoveSpeed { get; private set; } = 2.5f;
    [field : SerializeField] public float RunSpeed { get; private set; } = 4f;
    [field: SerializeField] public float DashForce { get; private set; } = 7f;

    public Vector2 moveDir { get; private set; } = Vector2.zero;    //ЧіРч РдЗТЙоРК РЬЕПАЊ Ёц W, A, S, D
    public Vector2 idleDir { get; private set; } = Vector2.zero;    //ЦЏСЄ ЙцЧтРЧ idle ОжДЯИоРЬМЧРЛ РчЛ§НУХАБт РЇЧи РЬЕПСпРЬ ОЦДЯОюЕЕ ИЖСіИЗПЁ ЧтЧпДј ЙцЧтРЛ БтОяЧиЕв
    public bool isSprint { get; private set; }              //ЧіРч ДоИЎДТ СпРЬИщ true
    public bool isCanDash { get; private set; } = true;     //ДыНЌАЁ АЁДЩЧб ЛѓХТ Ёц ЧіРч ДыНЌСпРЬ ОЦДЯАэ ДыНЌ Ф№ХИРгРЬ ЕЙОвРЛ ЖЇ
    public bool isDash { get; private set; }                //ЧіРч ДыНЌ СпРЬИщ true
    [SerializeField] private float dashTime = 0.1f;         //ДыНЌ МгЕЕЗЮ ЖйДТ НУАЃ
    [SerializeField] private float dashCoolTime = 1.5f;     //ДыНЌ Ф№ХИРг
    private Coroutine dashCoroutine;

    public bool isToolInteracted { get; private set; }      //РхКёИІ ТјПыЧб УЄЗЮ ЛѓШЃРлПыРЛ ЧпДТСі

    public Tool CurrentTool { get; private set; }           //ЧіРч ЧУЗЙРЬОюАЁ ЕщАэ РжДТ ЕЕБИ
    private IState currentState;                            //ЧіРч ЧУЗЙРЬОюРЧ ЛѓХТ

    private void Awake()
    {
        TryGetComponent(out playerRigid);

        //ЧУЗЙРЬОюАЁ ЕщАэРжДТ ЕЕБИЕщРЧ ЛѓХТ АДУМ Л§МК
        if(tools.Length > 0)
        {
            foreach(var tool in tools)
            {
                tool.SetState(this);
            }
        }

        #region РЮЧВНУНКХл ПЌАс
        OnMove();
        OnRun();
        OnDash();
        OnToolInteract();
        #endregion
    }

    private void Start()
    {
        GameManager.Instance.SetPlayer(this);

        //УЪБт ЛѓХТ МГСЄ
        SetState(new PlayerIdleState(this));
    }

    private void Update()
    {
        if (CurrentTool != null)
            GetTargetTilePosition();

        currentState?.OnUpdate();
    }

    private void FixedUpdate()
    {
        currentState?.OnFixedUpdate();
    }

    #region Input System
    //РЮЧВНУНКХлРИЗЮ ЙоОЦПРДТ РдЗТПЁ ЕћИЅ РЬКЅЦЎЕщ

    //АШБт РдЗТ Ёц W, A, S, D
    private void OnMove()
    {
        InputSystem.actions["Move"].performed += ctx =>
        {
            moveDir = ctx.ReadValue<Vector2>();
            idleDir = moveDir;
        };

        InputSystem.actions["Move"].canceled += ctx =>
        {
            moveDir = Vector2.zero;
        };
    }

    //ДоИЎБт РдЗТ Ёц ПоТЪ НЌЧСЦЎ
    private void OnRun()
    {
        InputSystem.actions["Sprint"].performed += ctx =>
        {
            isSprint = true;
        };

        InputSystem.actions["Sprint"].canceled += ctx =>
        {
            isSprint = false;
        };
    }

    //ДыНЌ РдЗТ Ёц НКЦфРЬНКЙй
    private void OnDash()
    {
        InputSystem.actions["Dash"].started += ctx =>
        {
            if (!isDash && isCanDash)
            {
                isDash = true;
                isCanDash = false;
            }
        };
    }

    //ЕЕБИ ЛѓШЃРлПы ХА РдЗТ Ёц ПоТЪ ИЖПьНКЙіЦА
    private void OnToolInteract()
    {
        InputSystem.actions["ToolInteract"].started += ctx =>
        {
            if(GameManager.Instance.CurrentGameState == GameState.Playing && CurrentTool != null)
            {
                isToolInteracted = true;
            }
        };

        InputSystem.actions["ToolInteract"].canceled += ctx =>
        {
            if (CurrentTool != null)
            {
                isToolInteracted = false;
            }
        };
    }
    #endregion

    //ЛѓХТ КЏАц
    public void SetState(IState state)
    {
        currentState?.OnExit();
        currentState = state;
        currentState?.OnEnter();
    }

    //ЧУЗЙРЬОюАЁ МеПЁ ЕхДТ ЕЕБИ КЏАц
    public void SetPlayerTool(Tool tool)
    {
        if (CurrentTool == tool) return;

        CurrentTool = tool;
    }

    public void Activate()
    {
        if (CurrentTool == null) return;

        CurrentTool.Activate();
    }

    /// <summary>
    /// ИЖПьНКПЭ ЧУЗЙРЬОюРЧ РЇФЁИІ ХыЧи ЧУЗЙРЬОю БйУГ ХИРЯ СТЧЅИІ АшЛъ
    /// ЙнАц ЙќРЇ Ёц ЧУЗЙРЬОю СжКЏ Чб Ф­
    /// Ёс Ёс Ёс
    /// Ёс p Ёс
    /// Ёс Ёс Ёс
    /// </summary>
    private void GetTargetTilePosition()
    {
        if (GameManager.Instance.CurrentGameState != GameState.Playing) return;

        //КИСЄРЬ ГЁГ­ УжСО СТЧЅ
        Vector3Int result = Vector3Int.zero;

        //ИЖПьНК СТЧЅ ЙоОЦПРБт
        Vector3 mousePos = Camera.main.ScreenToWorldPoint(Mouse.current.position.ReadValue());
        mousePos.z = 0;

        //СТЧЅ РЇФЁ КИСЄ, ЧУЗЙРЬОю СжКЏ ХИРЯ ЧбФ­ БюСіИИ РћПыЕЧАд
        int pPosX = Mathf.FloorToInt(transform.position.x);    //ЧУЗЙРЬОюРЧ ЧіРч xСТЧЅИІ ХИРЯ СТЧЅЗЮ УГИЎЧЯБт РЇЧи МвМіСЁ ЙіИВ
        int pPosY = Mathf.FloorToInt(transform.position.y);    //ЧУЗЙРЬОюРЧ ЧіРч yСТЧЅИІ ХИРЯ СТЧЅЗЮ УГИЎЧЯБт РЇЧи МвМіСЁ ЙіИВ

        Vector3 dir = mousePos - new Vector3(pPosX, pPosY, 0);

        if (dir.x < 0)
            result.x = pPosX - 1;
        else if (dir.x < 1)
            result.x = pPosX;
        else
            result.x = pPosX + 1;

        if (dir.y < 0)
            result.y = pPosY - 1;
        else if (dir.y < 1)
            result.y = pPosY;
        else
            result.y = pPosY + 1;

        //idleDirПЁ ЧіРч ИЖПьНК СТЧЅ СжБт
        idleDir = new Vector2(mousePos.x - transform.position.x, mousePos.y - transform.position.y).normalized;
        TileManager.Instance.GetTile(result);
    }

    #region ОжДЯИоРЬМЧ КЏАц
    //Trigger ЦФЖѓЙЬХЭИІ РЬПыЧб ОжДЯИоРЬМЧ КЏАц
    public void SetAnimTrigger(string animName)
    {
        playerAnim.SetTrigger(animName);
    }

    //Bool ЦФЖѓЙЬХЭИІ РЬПыЧб ОжДЯИоРЬМЧ КЏАц
    public void SetAnimBool(string animName, bool isTrue)
    {
        playerAnim.SetBool(animName, isTrue);
    }

    //Blend TreeАЁ ЛчПыСпРЮ ЦФЖѓЙЬХЭИІ РЬПыЧб ОжДЯИоРЬМЧ КЏАц
    public void SetAnimBlend(params (string animName, float value)[] blendVal)
    {
        foreach(var b in blendVal)
        {
            playerAnim.SetFloat(b.animName, b.value);
        }
    }
    #endregion

    //РЬЕП
    public void Move()
    {
        playerRigid.linearVelocity = isSprint ? RunSpeed * moveDir : MoveSpeed * moveDir;
        SetAnimBlend(("moveX", moveDir.x), ("moveY", moveDir.y));
    }

    public void Dash()
    {
        if (dashCoroutine != null)
            StopCoroutine(dashCoroutine);

        dashCoroutine = StartCoroutine(CoDash());
    }

    private IEnumerator CoDash()
    {
        float timer = 0f;
        float dashCoolRemaining = dashCoolTime - dashTime;

        while (timer < dashTime)
        {
            timer += Time.deltaTime;

            //ДыНЌЧЯДТ ЕЕСпПЁ РЬЕПХАИІ ЖП МіЕЕ РжБт ЖЇЙЎПЁ ИЖСіИЗ МіФЁИІ БтОяЧЯАэ РжДТ idleDirРЛ ЛчПы
            playerRigid.linearVelocity = DashForce * idleDir;

            yield return CoroutineManager.waitForFixedUpdate;
        }

        //НЧСњРћРЮ ДыНЌДТ ГЁ
        isDash = false;

        yield return CoroutineManager.waitForSeconds(dashCoolRemaining);

        //ДыНЌ Ф№ХИРгРЬ ГЁГЊМ­ ДыНЌАЁ АЁДЩЧб ЛѓХТЗЮ КЏАц
        isCanDash = true;
    }

    private void OnDisable()
    {
        StopAllCoroutines();
    }
}
